### PR TITLE
feat: Add Well Flow Indicator function

### PR DESCRIPTION
**Pull request by CogniteJohan**
Adding function "calculate_xmt_prod_status" for Well Flow Indication

## Description
New function added to define if well is open

## Motivation and Context
See Jira Issue AH-1895

## How Has This Been Tested?
Added 8 tests to pytest

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (non-breaking change which improves implementation)
- [ ] Performance (non-breaking change which improves performance. Please add associated performance test and results)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Non-functional change (xml comments/documentation/etc)

## Contributor Checklist:

- [x] My code follows the code style of this project.
- [ ] I have added an example of my new feature and included it in the documentation.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** [document](https://cognitedata.github.io/indsl/contribute.html).
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] My Pull Request name follows the [naming convention](https://www.conventionalcommits.org/en/v1.0.0/) `fix: <description>`, `feat: <description>`, etc.

## Reviewer Checklist for Charts compliant functions:

- [ ] The docstrings of the new function follow the contributing [guidelines](https://cognitedata.github.io/indsl/contribute.html).
- [ ] The new function is professionally [documented](https://journal.emwa.org/writing-matters/whats-your-problem-a-practical-approach-to-scientific-document-design/article/2110/2047480612z2e00000000042.pdf)
- [ ] The new function and associated scripts are covered by one or more unit tests and code coverage did not decrease.
- [ ] The new function is accompanied by an example and it is included in the Gallery of Charts.
- [ ] The new function is reviewed in Chromatic. Access the storybook build results url and comment, approve or deny.
- [ ] All function inputs, arguments, and outputs have a supported data type and have human readable names.
- [ ] No code language is included in the description of the function or parameters (e.g use "polynomial order" instead of "poly_order")

### CODE REVIEW

**Review by simonecasolo — APPROVED** [review]

**Comment by CogniteJohan** [comment]
@simonecasolo when you review this, keep this in mind:
- The changes in the valve_parameters files were only to fix typing issues
- I organised the old pytests for "calculate_well_prod_status" in a separate Class so that we have two different classes for that function and our new "calculate_xmt_prod_status". But because of indentation and the addition of the "cls"-parameters for each function makes it look like I changes all the old tests. These are however unchanged.
- Please consider if any variable names can be improved. I do not know well flows very well. F.ex, I grouped master, annulus and xover-valves as "wellhead_valves" but if there is a better name for this or other variables, please give a better suggestion.
- I did not change the documentation as I am unsure how you want it to be. Should we remove the old "calculate_well_prod_status" from the doc but keep it as-is for now?

We can also go through the code and tests together later when you have read through the changes

**Comment by neringaalt** [comment]
@CogniteJohan @simonecasolo 
Is the new function going to be exposed to Charts UI?

**Comment by CogniteJohan** [comment]
@simonecasolo , @skepticalcat  I assume this is not supposed to be in Charts?

**Comment by simonecasolo** [comment]
Good question.
I would say not for now

**Comment by CogniteJohan** [comment]
@neringaalt As Simone commented, we keep this out of Charts for now. I would like @skepticalcat to have another review before be merge this into master. I have not updated documentation or added an example as I am unsure how to best do that. This is a change of some older function, but the name has changed so I guess documentation should be changed somewhat. Would love your input here @skepticalcat or @simonecasolo

**Comment by skepticalcat** [comment]
@CogniteJohan, @simonecasolo I think we can't remove the old well production function that easily because it is exposed to charts and there might be some charts using that. 
So we'd either have to replace the old code with the new one, or, if we keep the old function, we would need to change the docstrings of the function slightly to indicate the differences between those two algorithms. 

Even if the second one is not exposed to charts, it'll show up in the auto-generated docs, and currently we would have two very similar functions, with almost identical docs, but different names.

So, for now I'd suggest to change the docs for the xmt function to indicate the differences. Code looks great though!

**Review by skepticalcat — APPROVED** [review]
lgtm! Well (heh) done!

**Review by neringaalt — APPROVED** [review]

**Pull request merged**
